# format_table: Formats a table and saves it as an XLSX file.
# Input:
#   - cross_tab_data: Data generated by generate_cross_tab (cross-tabulation data).
#   - file_name: Name of the XLSX file to be saved.
# Output:
#   - Saves the formatted table as an XLSX file.
#
# Styles and Options:
#   - Font: Verdana, Font weight: Bold for column headers
#
# Example usage:
#   data <- data.frame(
#     y_factor = factor(c("A", "B", "A", "B", "A")),
#     x_factor = factor(c("X", "Y", "X", "Y", "Z"))
#   )
#   cross_tab_data <- generate_cross_tab(data, "y_factor", "x_factor")
#   format_table(cross_tab_data$count, "formatted_table.xlsx")
library(openxlsx)
# Modify the format_table function to accept the entire cross_tab_data list
format_table <- function(cross_tab_data, file_name) {
  # Extract the table data from the cross_tab_data list
  table_data <- cross_tab_data$table
  
  # Create an XLSX workbook
  wb <- createWorkbook()
  
  # Add the table data to a worksheet
  addWorksheet(wb, "Formatted Table")
  writeData(wb, "Formatted Table", table_data)
  
  # Define a custom theme for formatting
  custom_theme <- createStyle(
    fontSize = 12,
    textDecoration = "bold",
    halign = "center"
  )
  
  # Apply custom formatting to column headers
  addStyle(wb, sheet = "Formatted Table", rows = 1, cols = 1:ncol(table_data), style = custom_theme)
  
  # Save the formatted table as an XLSX file with a unique name
  unique_file_name <- paste0(file_name, "_", format(Sys.time(), "%Y%m%d%H%M%S"), ".xlsx")
  saveWorkbook(wb, unique_file_name)
  
  cat("Table formatted and saved as", unique_file_name, "\n")
}


# Example usage:
data <- data.frame(
  y_factor = factor(c("A", "B", "A", "B", "A")),
  x_factor = factor(c("X", "Y", "X", "Y", "Z"))
)
cross_tab_data <- generate_cross_tab(data, "y_factor", "x_factor")
print(cross_tab_data)
format_table(cross_tab_data$count, "formatted_table_3.xlsx")
